# Site specific settings
title: "aa13q.ru"
name: "aa13q"
keywords: "Qt, QML, Sailfish, Pebble, etc"
# baseurl: "/"
url: "http://aa13q.ru"
description: "aa13q personal web page"
cover: "/assets/img/cover.svg"
# fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "ru_RU"
# ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
# disqus: test
twitter: a_andreyev
# facebook: 
github: a-andreyev
google: yetanotherandreyev

# Build settings
markdown: kramdown
permalink: /:title/
gems:
  - jekyll-gist
